/**:
    ros__parameters:
        robot_description_planning:
# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
            default_velocity_scaling_factor: 0.1
            default_acceleration_scaling_factor: 0.1

            # Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
            # Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
            joint_limits:
              joint_arm_l0:
                has_velocity_limits: true
                max_velocity: 0.02
                has_acceleration_limits: true
                max_acceleration: 0.02
                max_position: 0.13
                min_position: 0.0
              joint_arm_l1:
                has_velocity_limits: true
                max_velocity: 0.02
                has_acceleration_limits: true
                max_acceleration: 0.02
                max_position: 0.13
                min_position: 0.0
              joint_arm_l2:
                has_velocity_limits: true
                max_velocity: 0.02
                has_acceleration_limits: true
                max_acceleration: 0.02
                max_position: 0.13
                min_position: 0.0
              joint_arm_l3:
                has_velocity_limits: true
                max_velocity: 0.02
                has_acceleration_limits: true
                max_acceleration: 0.02
                max_position: 0.13
                min_position: 0.0
              joint_gripper_finger_left:
                has_velocity_limits: true
                max_velocity: 0.07
                has_acceleration_limits: true
                max_acceleration: 0.07
                max_position: 2.0
                min_position: -2.0
              joint_gripper_finger_right:
                has_velocity_limits: true
                max_velocity: 0.07
                has_acceleration_limits: true
                max_acceleration: 0.07
                max_position: 2.0
                min_position: -2.0
              joint_head_pan:
                has_velocity_limits: true
                max_velocity: 0.5
                has_acceleration_limits: true
                max_acceleration: 1.0
                max_position: 1.5
                min_position: -3.9
              joint_head_tilt:
                has_velocity_limits: true
                max_velocity: 0.5
                has_acceleration_limits: true
                max_acceleration: 1.0
                max_position: 0.79
                min_position: -1.53
              joint_lift:
                has_velocity_limits: true
                max_velocity: 0.06
                has_acceleration_limits: true
                max_acceleration: 0.04
                max_position: 1.1
                min_position: 0.0
              joint_wrist_yaw:
                has_velocity_limits: true
                max_velocity: 0.5
                has_acceleration_limits: true
                max_acceleration: 1.0
                max_position: 4.0
                min_position: -1.75
              joint_wrist_pitch:
                has_velocity_limits: true
                max_velocity: 0.5
                has_acceleration_limits: true
                max_acceleration: 1.0
                max_position: 0.56
                min_position: -1.57
              joint_wrist_roll:
                has_velocity_limits: true
                max_velocity: 0.5
                has_acceleration_limits: true
                max_acceleration: 1.0
                max_position: 3.14
                min_position: -3.14
              position/x:
                has_velocity_limits: true
                max_velocity: 0.04
                has_acceleration_limits: true
                max_acceleration: 0.02
                max_position: 2.0
                min_position: -2.0
              position/y:
                has_velocity_limits: true
                max_velocity: 0.04
                has_acceleration_limits: true
                max_acceleration: 0.02
                max_position: 2.0
                min_position: -2.0
              position/theta:
                has_velocity_limits: true
                max_velocity: 0.1
                has_acceleration_limits: true
                max_acceleration: 0.1
                max_position: 5.0
                min_position: -5.0
